### ISSUE TITLE
Change rule collection so it only applies to items with URL

### ISSUE THREAD

**Issue by TessFerrandez** [OfficeDev/Outlook-Add-in-LinkRevealer#7]
Currently since the rule is Message or Appointment or URL it will apply to all messages, the rule should be (contains url) AND (is email OR appointment)
`<Rule xsi:type="RuleCollection" Mode="And">
    <Rule xsi:type="ItemHasKnownEntity" EntityType="Url" />
    <Rule xsi:type="RuleCollection" Mode="Or" >
      <Rule xsi:type="ItemIs" ItemType="Message" FormType="Read" />
      <Rule xsi:type="ItemIs" ItemType="Appointment" FormType="Read" />
    </Rule>
  </Rule>`

**Comment by AndrewJByrne** [comment]
I've decided to remove ItemHasKnownEntity clause. Instead, I have reverted to it showing for messages and appointments in Read mode. Running the revealer will pick up all URLs, and tell us when none are in the body.
